#!/bin/sh

if [ "$1" = "start" ]
then
	KERNELRELEASE=$(uname -r)

	rmmod hynitron_touch
	rmmod spi_gpio
	rmmod spi_bitbang
	rmmod i2c_gpio
	rmmod i2c_algo_bit

	. /etc/profile
	printf "load kernel module: "
	cd /usr/lib/vendor/system/ko/
	for ko in ${KERNELRELEASE}/*.ko ; do
		if [ -e $ko ]; then
			km=`basename $ko`
			rm -f $km
			ln -s $ko $km
		fi
	done
	mkdir -p 3rd
	for ko in ${KERNELRELEASE}/3rd/*.ko ; do
		if [ -e $ko ]; then
			km=`basename $ko`
			rm -f 3rd/$km
			ln -s ../$ko 3rd/$km
		fi
	done
	insmod soph_sys.ko
	insmod soph_base.ko
	insmod soph_tpu.ko
	insmod soph_mon.ko
	insmod soph_wiegand.ko
	echo "OK"
	exit 0
fi
