name: Build Image
on:
  workflow_dispatch:
  
jobs:     
  build-image:
    strategy:
      matrix:
        boards: [licheervnano]
        variant: [e]
        storage: [sd]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Get Board Configs
        uses: actions/checkout@v4
      - name: Build Images
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/scpcom/sophgo-sg200x-debian:debian
          options: --privileged -v ${{ github.workspace }}/images/:/output -v ${{ github.workspace }}/configs/:/configs/  -v ${{ github.workspace }}/scripts/:/builder
          run: |
            make BOARD=${{ matrix.boards }} VARIANT=${{ matrix.variant }} STORAGE_TYPE=${{ matrix.storage }} image
            chmod 777 /output/
      - name: Pack
        run: |
          cd images/
          ls -lah
          tar czvf ${{ matrix.boards }}-${{ matrix.variant }}-${{ matrix.storage }}_debs.tar.gz *.deb
          rm *.deb
          echo "PACKAGE=${{ github.workspace }}/images/*" >> $GITHUB_ENV
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: image-files-${{ matrix.boards }}-${{ matrix.variant }}-${{ matrix.storage }}
          path: |
            ${{env.PACKAGE}}
  release:
    runs-on: ubuntu-latest
    needs: [build-image]
    permissions: write-all
    steps:
      - name: download firmware
        uses: actions/download-artifact@v4
      - name: list images
        run: |
          ls -lah
          ls -lah image-files-*/
      - name: publish artifacts
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN_RELEASES }}
          append_body: true
          files: |
            image-files-*/*
